### PR TITLE
Bugfixes and features

### PR DESCRIPTION
**Pull request by srand**
Hi,

Please consider merging these bugfixes and new features.

Thanks in advance
/Robert

### CODE REVIEW

**Comment by troglobit** [comment]
Wow, looks great, thank you! :sunglasses::+1:

**Comment by abucodonosor** [comment]
@troglobit @srand 

I know this is merged && closed but   'fix service enable/disable support'  seems to hardcode
/etc/finit.d.. 

...
 glob("/etc/finit.d/*.conf", 0, NULL, &gl);
 glob("/etc/finit.d/enabled/*.conf", GLOB_APPEND, NULL, &gl);
...

However this is configurable .. so probably use FINIT_RCSD ?

**Comment by troglobit** [comment]
@abucodonosor Good catch!  I'll be travelling for the next few days, but pull requests are open.

**Comment by abucodonosor** [comment]
@srand @troglobit 

plugins/modules-load.c:

#define MODULES_LOAD_PATH "/etc/modules-load.d" <-- can that dir be made configurable please ?
peoples without systemd or custom loading aka !kmod won't have that dir in this path.

 ":%d name:modprobe.%s [2345] /sbin/modprobe %s %s -- Kernel module: %s"

Same this .. peoples may use /some_path/load_my_modules ..

Also I would at least 'check ' modprobe exists et all before doing anything .

Also maybe use if (fisdir("DIR_TO_CHECK")) ..

**Comment by abucodonosor** [comment]
@troglobit 

:) I'm travelling too is why I got some time to look a bit around in finit source.

**Pull request merged**
