### PR TITLE
initctl signal

### PR DESCRIPTION
**Pull request by jorgensigvardsson**
Implements the feature requested in #225.

`initctl` has been changed in the following way:
- it has been augmented with a new command: `signal`. The command requires two arguments: the service to signal, and the signal itself.
- the signal can be a complete signal name such as `SIGHUP`, or a short name such as `HUP`, or the signal number such as `1`
- man page for `initctl` has been updated accordingly

Please note that internal APIs have been changed:
- `initctl` has been modified such that it can implement multi argument commands. Please see `cb_multiarg` of `struct cmd` in `initctl.c`. Changes are backwards compatible with existing code (old command handlers have not been changed).
- `svc_parse_jobstr` from `svc.{h,c}` has been extended so that it can pass on user data to any of its callbacks. The reasoning is that I wanted to reuse a lot of existing code that did most of what's needed. The needed functionality was to pass the actual signal number to the callback: this is done using the `user_data` parameter.

### CODE REVIEW

**Comment by troglobit** [comment]
Build and test pass! \o/

I'll have to postpone the review for tomorrow, it got a bit too late tonight, sorry.  From a *very* quick look it seems most of my feedback will be around grammar, commit message style, and such trivial matters -- which I know will be important for you to learn going forward in other upstream projects as well.

**Comment by jorgensigvardsson** [comment]
Sorry about the commit spam to this PR. I have just learned that one should definitely `make distclean` et al, and build everything from scratch. Did some changes to test scripts, ran `make check` - everything checked out. Committed and pushed, and still it failed in the github workflows. Only when I cleaned and built everything from scratch did I notice the exact same problems.

**Comment by troglobit** [comment]
@jorgensigvardsson there's a actually `make distcheck` build target for that, very handy and what I call in my `release` target :)

**Comment by troglobit** [comment]
Sorry for checking back so late on this, but as you know, it was crazy buys at $DAYJOB this past week!  :disappointed: 

The PR looks great, only really had one or two minor nitpicks, but I'll fix up manually and merge anyway. If you're curious, check the follow-up commits later today.

The stuff that sticks out, however, are the commit messages.  I'll just mention a thing or two about it here, for future reference:

   * When fixing a bug/feature in the issue tracker, say `"Fix #225: initctl support for sending signals to services"`.  So when the maintainer merges to master, GitHub will automatically close issue `#225`. I'll add it now to the merge commit instead. The PR text itself, which is similar to a mailing list cover letter will be lost and only stored with GitHub, so some text should be in the commit that ties it all together.  I.e., `"This patch implements the `initctl signal` command using the recently added API for signaling ... "`
   * Always use present tense, i.e., `"Add implementation for ..."`

**Pull request merged**
